"""
Link Service — Matriz de vinculación (BLUEPRINT RFC-0001 §3.2)
==============================================================
Una sola tabla (service_links) genera:
  1. NetworkPolicies k8s (default-deny + allows puntuales por link)
  2. Variables de entorno {ALIAS}_HOST / {ALIAS}_PORT / {ALIAS}_URL
     (mismo contrato que database_bindings: literals para secretGenerator)
  3. El diagrama de arquitectura (nodos/aristas/grupos) — es un SELECT renderizado

Los manifiestos generados siguen las convenciones existentes de infra-gitops:
labels software-factory.io/*, comentario "generated by Kaanbal Engine",
archivo netpol-<app>.yaml dentro de overlays/<env>/.
"""

from typing import Dict, List, Optional, Any

# Puertos lógicos → esquema de URL para la variable {ALIAS}_URL
_SCHEME_BY_PORT_NAME = {
    "http": "http",
    "api": "http",
    "dashboard": "http",
    "ws": "ws",
    "websocket": "ws",
    "mqtt": "mqtt",
    "db": "postgresql",
    "postgres": "postgresql",
    "mongo": "mongodb",
    "mongodb": "mongodb",
    "redis": "redis",
    "s3": "http",
    "grpc": "grpc",
}

# Namespaces de infraestructura que pueden alcanzar apps según visibilidad
_INGRESS_NAMESPACE = "ingress-nginx"
_TAILSCALE_NAMESPACE = "tailscale"


def default_alias(app_name: str) -> str:
    """shop-bd-postgres → SHOP_BD_POSTGRES (mismo patrón que database_bindings)"""
    return app_name.upper().replace("-", "_").replace(".", "_")


def service_fqdn(app_name: str, env: str) -> str:
    """DNS interno del Service k8s: <app>.<env>.svc.cluster.local"""
    return f"{app_name}.{env}.svc.cluster.local"


def build_env_literals(link: dict) -> List[str]:
    """Literals estilo secretGenerator para inyectar en la app consumidora.

    Contrato idéntico al de database_bindings: {ALIAS}_HOST, {ALIAS}_PORT,
    {ALIAS}_URL. Los bindings de BD siguen agregando DATABASE/USER/PASSWORD
    por su flujo propio — esto es el caso general.
    """
    alias = link.get("alias") or default_alias(link["to_app"])
    host = service_fqdn(link["to_app"], link["to_env"])
    port = link.get("port_number") or 80
    scheme = _SCHEME_BY_PORT_NAME.get(link.get("port_name", "http"), "http")
    return [
        f"{alias}_HOST={host}",
        f"{alias}_PORT={port}",
        f"{alias}_URL={scheme}://{host}:{port}",
    ]


def _netpol_ingress_rule_for_link(link: dict) -> str:
    """Regla de allow para UN link entrante (consumidor → proveedor).

    Cross-namespace: namespaceSelector por nombre + podSelector por app.
    """
    port = link.get("port_number")
    port_block = ""
    if port:
        port_block = (
            "      ports:\n"
            "        - protocol: TCP\n"
            f"          port: {port}\n"
        )
    return (
        "    - from:\n"
        "        - namespaceSelector:\n"
        "            matchLabels:\n"
        f"              kubernetes.io/metadata.name: {link['from_env']}\n"
        "          podSelector:\n"
        "            matchLabels:\n"
        f"              app: {link['from_app']}\n"
        + port_block
    )


def _netpol_infra_rule(namespace: str) -> str:
    """Allow desde un namespace de infraestructura (ingress-nginx / tailscale)."""
    return (
        "    - from:\n"
        "        - namespaceSelector:\n"
        "            matchLabels:\n"
        f"              kubernetes.io/metadata.name: {namespace}\n"
    )


def generate_network_policy(
    app_name: str,
    env: str,
    inbound_links: List[dict],
    has_public_port: bool = False,
    has_vpn_port: bool = False,
) -> str:
    """NetworkPolicy YAML para una app en un ambiente.

    Semántica: default-deny de ingress hacia los pods de la app, con allows:
      - un allow por cada ServiceLink entrante (app-scoped real)
      - allow desde ingress-nginx si algún puerto es público
      - allow desde tailscale si algún puerto es vpn
    El egress no se restringe en v1 (aditivo después).
    """
    rules = []
    if has_public_port:
        rules.append(_netpol_infra_rule(_INGRESS_NAMESPACE))
    if has_vpn_port:
        rules.append(_netpol_infra_rule(_TAILSCALE_NAMESPACE))
    for link in inbound_links:
        rules.append(_netpol_ingress_rule_for_link(link))

    if rules:
        ingress_block = "  ingress:\n" + "".join(rules)
    else:
        # Sin links ni exposición: nadie entra (default-deny puro)
        ingress_block = "  ingress: []\n"

    return (
        f"# Auto-generated NetworkPolicy from ServiceLinks - Kaanbal Engine\n"
        f"# Fuente de verdad: colección service_links (no editar a mano)\n"
        f"apiVersion: networking.k8s.io/v1\n"
        f"kind: NetworkPolicy\n"
        f"metadata:\n"
        f"  name: {app_name}-links\n"
        f"  namespace: {env}\n"
        f"  labels:\n"
        f"    app: {app_name}\n"
        f"    software-factory.io/generated: service-links\n"
        f"spec:\n"
        f"  podSelector:\n"
        f"    matchLabels:\n"
        f"      app: {app_name}\n"
        f"  policyTypes:\n"
        f"    - Ingress\n"
        + ingress_block
    )


def generate_policies_for_env(
    env: str,
    links: List[dict],
    app_exposures: Optional[Dict[str, Dict[str, bool]]] = None,
) -> Dict[str, str]:
    """Genera todas las NetworkPolicies de un ambiente.

    Devuelve { app_name: yaml } solo para apps que son PROVEEDORAS de al menos
    un link en ese env (opt-in gradual: apps sin links no se tocan, así el
    default-deny no rompe nada existente hasta que el usuario vincula).

    app_exposures: { app_name: {"public": bool, "vpn": bool} } — derivado de
    ExposureConfig.port_exposure para conservar el acceso de ingress/tailnet.
    """
    app_exposures = app_exposures or {}
    providers: Dict[str, List[dict]] = {}
    for link in links:
        if link["to_env"] == env:
            providers.setdefault(link["to_app"], []).append(link)

    manifests = {}
    for app_name, inbound in providers.items():
        exposure = app_exposures.get(app_name, {})
        manifests[app_name] = generate_network_policy(
            app_name,
            env,
            inbound,
            has_public_port=exposure.get("public", False),
            has_vpn_port=exposure.get("vpn", False),
        )
    return manifests


# ============ DIAGRAMA (nodos/aristas/grupos) ============

def build_diagram(
    apps: List[dict],
    links: List[dict],
    domains: List[dict],
    sites: Optional[List[dict]] = None,
) -> Dict[str, Any]:
    """Modelo de diagrama para la consola (vis.js / mermaid / d3).

    Nodos especiales: internet, vpn. Grupos: dominios y sites.
    Es literalmente un SELECT sobre apps + service_links + domains + sites.
    """
    sites = sites or []
    default_domain = next((d for d in domains if d.get("is_default")), None)

    nodes = [
        {"id": "internet", "type": "internet", "label": "Internet"},
        {"id": "vpn", "type": "vpn", "label": "VPN (tailnet)"},
    ]
    edges = []
    groups = []

    for domain in domains:
        groups.append({
            "id": f"domain:{domain['fqdn']}",
            "type": "domain",
            "label": domain["fqdn"],
            "client_id": domain.get("client_id"),
        })
    for site in sites:
        groups.append({
            "id": f"site:{site['name']}",
            "type": f"site-{site.get('type', 'cloud')}",
            "label": site["name"],
            "client_id": site.get("client_id"),
            "status": site.get("status"),
        })

    for app in apps:
        domain_fqdn = None
        if app.get("domain_id"):
            match = next((d for d in domains if str(d.get("_id")) == str(app["domain_id"])), None)
            domain_fqdn = match["fqdn"] if match else None
        if not domain_fqdn and default_domain:
            domain_fqdn = default_domain["fqdn"]

        node = {
            "id": app["name"],
            "type": "app",
            "label": app["name"],
            "template": app.get("template"),
            "environments": app.get("environments", []),
            "group": f"domain:{domain_fqdn}" if domain_fqdn else None,
            "client_id": app.get("client_id"),
            "status": app.get("status"),
        }
        nodes.append(node)

        # Aristas de exposición: derivadas de exposure (public/vpn)
        exposure = app.get("exposure") or {}
        exp_type = exposure.get("type", "internal")
        if exp_type in ("public", "both"):
            edges.append({"from": "internet", "to": app["name"], "kind": "exposure-public"})
        if exp_type in ("tailscale", "both"):
            edges.append({"from": "vpn", "to": app["name"], "kind": "exposure-vpn"})
        port_exposure = exposure.get("port_exposure") or {}
        for env_map in port_exposure.values():
            for port_name, level in env_map.items():
                if level == "public":
                    edges.append({"from": "internet", "to": app["name"], "kind": "exposure-public", "port": port_name})
                elif level == "tailscale":
                    edges.append({"from": "vpn", "to": app["name"], "kind": "exposure-vpn", "port": port_name})

    for link in links:
        edges.append({
            "from": link["from_app"],
            "to": link["to_app"],
            "kind": "service-link",
            "from_env": link["from_env"],
            "to_env": link["to_env"],
            "port": link.get("port_name"),
            "visibility": link.get("visibility"),
            "alias": link.get("alias"),
        })

    # Deduplicar aristas de exposición idénticas
    seen = set()
    unique_edges = []
    for edge in edges:
        key = (edge["from"], edge["to"], edge["kind"], edge.get("port"), edge.get("from_env"), edge.get("to_env"))
        if key not in seen:
            seen.add(key)
            unique_edges.append(edge)

    return {"nodes": nodes, "edges": unique_edges, "groups": groups}
