"""EMQX Edge managed-service helpers (profile + MQTT auth bootstrap Job).

Kept separate from AppDeployer to avoid `if template_id == "emqx"` sprawl.
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional


TOPIC_PREFIX_DEFAULT = "acuaponia"

BOOTSTRAP_SECRET_KEYS = [
    "EMQX_DASHBOARD__DEFAULT_USERNAME",
    "EMQX_DASHBOARD__DEFAULT_PASSWORD",
    "EMQX_MQTT_DEVICE_USERNAME",
    "EMQX_MQTT_DEVICE_PASSWORD",
    "EMQX_MQTT_FRONTEND_USERNAME",
    "EMQX_MQTT_FRONTEND_PASSWORD",
    "EMQX_TOPIC_PREFIX",
]


def is_emqx_template(template_id: str = "", category: str = "", template_details: Optional[dict] = None) -> bool:
    tid = (template_id or "").lower()
    cat = (category or "").lower()
    if "emqx" in tid:
        return True
    if cat == "iot" and template_details and (template_details.get("id") or "").lower() == "emqx":
        return True
    return bool(template_details and (template_details.get("id") or "").lower() == "emqx")


def edge_secret_schema(topic_prefix: str = TOPIC_PREFIX_DEFAULT) -> List[dict]:
    """Extra secrets beyond dashboard admin (device + frontend MQTT users)."""
    return [
        {"name": "EMQX_DASHBOARD__DEFAULT_USERNAME", "auto_generate": False, "pattern": "admin"},
        {"name": "EMQX_DASHBOARD__DEFAULT_PASSWORD", "auto_generate": True, "length": 24},
        {"name": "EMQX_MQTT_DEVICE_USERNAME", "auto_generate": False, "pattern": "device"},
        {"name": "EMQX_MQTT_DEVICE_PASSWORD", "auto_generate": True, "length": 24},
        {"name": "EMQX_MQTT_FRONTEND_USERNAME", "auto_generate": False, "pattern": "frontend"},
        {"name": "EMQX_MQTT_FRONTEND_PASSWORD", "auto_generate": True, "length": 24},
        {"name": "EMQX_TOPIC_PREFIX", "auto_generate": False, "pattern": topic_prefix},
    ]


def render_bootstrap_job(
    app_name: str,
    *,
    namespace: str = "prod",
    topic_prefix: str = TOPIC_PREFIX_DEFAULT,
    dashboard_port: int = 18083,
) -> str:
    """Idempotent Job: wait for EMQX API, enable password auth, create users + ACL."""
    # Uses busybox+curl image; talks to ClusterIP service on dashboard port.
    return f"""# EMQX Edge MQTT auth bootstrap — generated by Kaanbal
apiVersion: batch/v1
kind: Job
metadata:
  name: {app_name}-mqtt-bootstrap
  labels:
    app: {app_name}
    software-factory.io/role: mqtt-bootstrap
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 6
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      labels:
        app: {app_name}
        software-factory.io/role: mqtt-bootstrap
    spec:
      restartPolicy: OnFailure
      containers:
        - name: bootstrap
          image: curlimages/curl:8.5.0
          envFrom:
            - secretRef:
                name: {app_name}-secrets
                optional: false
          env:
            - name: EMQX_API
              value: "http://{app_name}.{namespace}.svc.cluster.local:{dashboard_port}"
            - name: TOPIC_PREFIX
              value: "{topic_prefix}"
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -eu
              ADMIN_USER="${{EMQX_DASHBOARD__DEFAULT_USERNAME:-admin}}"
              ADMIN_PASS="${{EMQX_DASHBOARD__DEFAULT_PASSWORD}}"
              DEVICE_USER="${{EMQX_MQTT_DEVICE_USERNAME:-device}}"
              DEVICE_PASS="${{EMQX_MQTT_DEVICE_PASSWORD}}"
              FRONT_USER="${{EMQX_MQTT_FRONTEND_USERNAME:-frontend}}"
              FRONT_PASS="${{EMQX_MQTT_FRONTEND_PASSWORD}}"
              PREFIX="${{EMQX_TOPIC_PREFIX:-$TOPIC_PREFIX}}"
              API="$EMQX_API"
              AUTH="Authorization: Basic $(printf '%s:%s' "$ADMIN_USER" "$ADMIN_PASS" | base64 | tr -d '\\n')"

              echo "Waiting for EMQX API at $API ..."
              i=0
              until curl -sf -H "$AUTH" "$API/api/v5/status" >/dev/null 2>&1 \\
                 || curl -sf -u "$ADMIN_USER:$ADMIN_PASS" "$API/api/v5/status" >/dev/null 2>&1; do
                i=$((i+1))
                if [ "$i" -gt 60 ]; then
                  echo "EMQX API not ready after 5m" >&2
                  exit 1
                fi
                sleep 5
              done
              echo "EMQX API is up"

              # Prefer -u for Basic auth (dashboard credentials)
              curl_api() {{
                method="$1"; path="$2"; shift 2
                curl -sS -u "$ADMIN_USER:$ADMIN_PASS" -X "$method" \\
                  -H "Content-Type: application/json" \\
                  "$API$path" "$@"
              }}

              # Ensure password-based authenticator exists (built_in_database)
              AUTH_ID="password_based:built_in_database"
              CODE=$(curl -sS -o /tmp/auth.json -w "%{{http_code}}" -u "$ADMIN_USER:$ADMIN_PASS" \\
                "$API/api/v5/authentication/$AUTH_ID" || true)
              if [ "$CODE" = "404" ]; then
                echo "Creating authenticator $AUTH_ID"
                curl_api POST "/api/v5/authentication" -d '{{
                  "mechanism": "password_based",
                  "backend": "built_in_database",
                  "enable": true,
                  "user_id_type": "username",
                  "password_hash_algorithm": {{"name": "sha256", "salt_position": "suffix"}}
                }}' >/tmp/auth-create.json || true
              else
                echo "Authenticator present (HTTP $CODE)"
              fi

              upsert_user() {{
                user="$1"; pass="$2"
                CODE=$(curl -sS -o /tmp/user.json -w "%{{http_code}}" -u "$ADMIN_USER:$ADMIN_PASS" \\
                  "$API/api/v5/authentication/$AUTH_ID/users/$user" || true)
                if [ "$CODE" = "200" ]; then
                  echo "Updating user $user"
                  curl_api PUT "/api/v5/authentication/$AUTH_ID/users/$user" \\
                    -d "{{\\"password\\": \\"$pass\\"}}" >/tmp/user-upd.json || true
                else
                  echo "Creating user $user"
                  curl_api POST "/api/v5/authentication/$AUTH_ID/users" \\
                    -d "{{\\"user_id\\": \\"$user\\", \\"password\\": \\"$pass\\"}}" >/tmp/user-add.json || true
                fi
              }}

              upsert_user "$DEVICE_USER" "$DEVICE_PASS"
              upsert_user "$FRONT_USER" "$FRONT_PASS"

              # Authorization sources — allow all for device under prefix; frontend subscribe-only
              # EMQX 5 built-in ACL via authorization settings (best-effort; may already exist)
              curl_api PUT "/api/v5/authorization/settings" -d '{{
                "no_match": "allow",
                "deny_action": "ignore",
                "cache": {{"enable": true}}
              }}' >/tmp/authz.json || true

              echo "Bootstrap complete for prefix=$PREFIX users=$DEVICE_USER,$FRONT_USER"
"""


def connection_hints(
    app_name: str,
    env: str,
    *,
    domain: str = "",
    lan_ip: str = "",
    ts_suffix: str = "",
    topic_prefix: str = TOPIC_PREFIX_DEFAULT,
) -> Dict[str, Any]:
    """Static URL hints (caller should overwrite with probed values)."""
    ns = env
    internal_host = f"{app_name}.{ns}.svc.cluster.local"
    out: Dict[str, Any] = {
        "internal": {
            "mqtt": f"mqtt://{internal_host}:1883",
            "websocket": f"ws://{internal_host}:8083/mqtt",
            "dashboard": f"http://{internal_host}:18083",
        },
        "users": {
            "dashboard": "admin (EMQX_DASHBOARD__*)",
            "device": "device → publish/subscribe under {prefix}/#",
            "frontend": "frontend → subscribe-only recommended",
        },
        "topic_prefix": topic_prefix,
    }
    if lan_ip:
        out["lan"] = {
            "mqtt": f"mqtt://{lan_ip}:1883",
            "websocket": f"ws://{lan_ip}:8083/mqtt",
            "dashboard": f"http://{lan_ip}:18083",
        }
    if ts_suffix:
        out["tailscale"] = {
            "mqtt": f"mqtt://{env}-{app_name}-mqtt.{ts_suffix}:1883",
            "websocket": f"ws://{env}-{app_name}-ws.{ts_suffix}:8083/mqtt",
            "dashboard": f"http://{env}-{app_name}-dashboard.{ts_suffix}:18083",
        }
    if domain:
        out["public"] = {
            "websocket": f"wss://mqtt-{app_name}.{domain}/mqtt",
        }
    return out
