apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datastore-data
  labels:
    app: datastore
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
