apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: dev
nameSuffix: -dev

patchesStrategicMerge:
  - patch-deployment-env.yaml
  - patch-deployment-labels.yaml
  - patch-bootstrap-admin-delete.yaml
  - patch-ingress-delete.yaml
  - patch-rbac-dev.yaml

images:
  - name: kaanbal-api-image
    newName: DOCKERHUB_USER/kaanbal-api
    newTag: latest